"""initial schema

Revision ID: 7532ab95d30a
Revises: 
Create Date: 2026-09-14 19:40:15.114478
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7532ab95d30a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_runs_job_name'), ['job_name'], unique=False)

    op.create_table('products',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('subcategory', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gtin', sa.String(length=20), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('mpn', sa.String(length=100), nullable=True),
    sa.Column('asin', sa.String(length=20), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('specifications', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('images', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('normalized_name', sa.String(length=500), nullable=True),
    sa.Column('canonical_key', sa.String(length=300), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_asin'), ['asin'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_canonical_key'), ['canonical_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_gtin'), ['gtin'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_mpn'), ['mpn'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_sku'), ['sku'], unique=False)

    op.create_table('retailers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('is_marketplace', sa.Boolean(), nullable=False),
    sa.Column('is_curated', sa.Boolean(), nullable=False),
    sa.Column('policies', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('retailers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retailers_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_retailers_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('google_sub', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('notification_preferences', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('webhook_events',
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_webhook_provider_event')
    )
    op.create_table('product_variants',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('storage', sa.String(length=30), nullable=True),
    sa.Column('ram', sa.String(length=30), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('size', sa.String(length=60), nullable=True),
    sa.Column('configuration', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=True),
    sa.Column('gtin', sa.String(length=20), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('mpn', sa.String(length=100), nullable=True),
    sa.Column('asin', sa.String(length=20), nullable=True),
    sa.Column('canonical_key', sa.String(length=300), nullable=True),
    sa.Column('additional_specs', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_key')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variants_asin'), ['asin'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variants_gtin'), ['gtin'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variants_product_id'), ['product_id'], unique=False)

    op.create_table('refresh_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('review_analysis',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('positive_themes', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('negative_themes', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('delivery_score', sa.Integer(), nullable=True),
    sa.Column('packaging_score', sa.Integer(), nullable=True),
    sa.Column('authenticity_score', sa.Integer(), nullable=True),
    sa.Column('service_score', sa.Integer(), nullable=True),
    sa.Column('suspicious_pattern_detected', sa.Boolean(), nullable=False),
    sa.Column('suspicious_signals', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_analysis_product_id'), ['product_id'], unique=False)

    op.create_table('reviews',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('retailer_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=200), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=False),
    sa.Column('review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_product_id'), ['product_id'], unique=False)

    op.create_table('saved_products',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_saved_product_user_product')
    )
    with op.batch_alter_table('saved_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_products_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_products_user_id'), ['user_id'], unique=False)

    op.create_table('searches',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('query_type', sa.String(length=20), nullable=True),
    sa.Column('query_url', sa.Text(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('filters', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('data_mode', sa.String(length=10), nullable=True),
    sa.Column('providers_used', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_searches_user_id'), ['user_id'], unique=False)

    op.create_table('sellers',
    sa.Column('retailer_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retailer_id', 'name', name='uq_seller_retailer_name')
    )
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sellers_retailer_id'), ['retailer_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_provider_subscription_id'), ['provider_subscription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('trust_events',
    sa.Column('retailer_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('weight', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trust_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trust_events_retailer_id'), ['retailer_id'], unique=False)

    op.create_table('community_reports',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('retailer_id', sa.Uuid(), nullable=True),
    sa.Column('seller_id', sa.Uuid(), nullable=True),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('order_reference_hash', sa.String(length=64), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('moderation_status', sa.String(length=20), nullable=False),
    sa.Column('moderation_note', sa.Text(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flag_count', sa.Integer(), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_reports_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_reports_retailer_id'), ['retailer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_reports_user_id'), ['user_id'], unique=False)

    op.create_table('offers',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('retailer_id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('listed_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('shipping_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_known', sa.Boolean(), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('coupon_code', sa.String(length=100), nullable=True),
    sa.Column('coupon_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_final_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('final_price_known', sa.Boolean(), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=True),
    sa.Column('delivery_text', sa.String(length=200), nullable=True),
    sa.Column('cod_available', sa.Boolean(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('match_type', sa.String(length=40), nullable=False),
    sa.Column('match_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('match_reasons', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_engine', sa.String(length=50), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_retailer_id'), ['retailer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offers_variant_id'), ['variant_id'], unique=False)

    op.create_table('payments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_order_id', sa.String(length=100), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_via', sa.String(length=20), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_order_id', name='uq_payment_provider_order'),
    sa.UniqueConstraint('provider_payment_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_provider_order_id'), ['provider_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('price_alerts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('drop_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('baseline_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_lowest_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_triggered', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_method', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_alerts_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('trust_evidence',
    sa.Column('retailer_id', sa.Uuid(), nullable=True),
    sa.Column('seller_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('topic', sa.String(length=40), nullable=False),
    sa.Column('sentiment', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('severity', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('extracted_claim', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    with op.batch_alter_table('trust_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_trust_evidence_retailer_collected', ['retailer_id', 'collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_evidence_retailer_id'), ['retailer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_evidence_seller_id'), ['seller_id'], unique=False)

    op.create_table('trust_scores',
    sa.Column('retailer_id', sa.Uuid(), nullable=True),
    sa.Column('seller_id', sa.Uuid(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('factors', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('concerns', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('component_scores', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('methodology_version', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trust_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trust_scores_retailer_id'), ['retailer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trust_scores_seller_id'), ['seller_id'], unique=False)

    op.create_table('affiliate_clicks',
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('retailer_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('destination_url', sa.Text(), nullable=False),
    sa.Column('affiliate_applied', sa.Boolean(), nullable=False),
    sa.Column('program', sa.String(length=50), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('referer', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affiliate_clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliate_clicks_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_clicks_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_clicks_retailer_id'), ['retailer_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['price_alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('price_history',
    sa.Column('offer_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('retailer_id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=True),
    sa.Column('listed_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_final_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retailer_id'], ['retailers.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_offer_id'), ['offer_id'], unique=False)
        batch_op.create_index('ix_price_history_product_observed', ['product_id', 'observed_at'], unique=False)
        batch_op.create_index('ix_price_history_retailer_observed', ['retailer_id', 'observed_at'], unique=False)

    op.create_table('report_flags',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['community_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'user_id', name='uq_report_flag_user')
    )
    with op.batch_alter_table('report_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_flags_report_id'), ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_flags_report_id'))

    op.drop_table('report_flags')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_price_history_retailer_observed')
        batch_op.drop_index('ix_price_history_product_observed')
        batch_op.drop_index(batch_op.f('ix_price_history_offer_id'))

    op.drop_table('price_history')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('affiliate_clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliate_clicks_retailer_id'))
        batch_op.drop_index(batch_op.f('ix_affiliate_clicks_product_id'))
        batch_op.drop_index(batch_op.f('ix_affiliate_clicks_offer_id'))

    op.drop_table('affiliate_clicks')
    with op.batch_alter_table('trust_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trust_scores_seller_id'))
        batch_op.drop_index(batch_op.f('ix_trust_scores_retailer_id'))

    op.drop_table('trust_scores')
    with op.batch_alter_table('trust_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trust_evidence_seller_id'))
        batch_op.drop_index(batch_op.f('ix_trust_evidence_retailer_id'))
        batch_op.drop_index('ix_trust_evidence_retailer_collected')

    op.drop_table('trust_evidence')
    with op.batch_alter_table('price_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_alerts_user_id'))
        batch_op.drop_index(batch_op.f('ix_price_alerts_product_id'))

    op.drop_table('price_alerts')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_provider_order_id'))

    op.drop_table('payments')
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_variant_id'))
        batch_op.drop_index(batch_op.f('ix_offers_retailer_id'))
        batch_op.drop_index(batch_op.f('ix_offers_product_id'))

    op.drop_table('offers')
    with op.batch_alter_table('community_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_reports_retailer_id'))
        batch_op.drop_index(batch_op.f('ix_community_reports_product_id'))

    op.drop_table('community_reports')
    with op.batch_alter_table('trust_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trust_events_retailer_id'))

    op.drop_table('trust_events')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_provider_subscription_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sellers_retailer_id'))

    op.drop_table('sellers')
    with op.batch_alter_table('searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_searches_user_id'))

    op.drop_table('searches')
    with op.batch_alter_table('saved_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_products_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_products_product_id'))

    op.drop_table('saved_products')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_product_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('review_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_analysis_product_id'))

    op.drop_table('review_analysis')
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_user_id'))

    op.drop_table('refresh_sessions')
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_variants_gtin'))
        batch_op.drop_index(batch_op.f('ix_product_variants_asin'))

    op.drop_table('product_variants')
    op.drop_table('webhook_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('retailers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retailers_slug'))
        batch_op.drop_index(batch_op.f('ix_retailers_domain'))

    op.drop_table('retailers')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_sku'))
        batch_op.drop_index(batch_op.f('ix_products_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_products_mpn'))
        batch_op.drop_index(batch_op.f('ix_products_gtin'))
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.drop_index(batch_op.f('ix_products_canonical_key'))
        batch_op.drop_index(batch_op.f('ix_products_brand'))
        batch_op.drop_index(batch_op.f('ix_products_asin'))

    op.drop_table('products')
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_runs_job_name'))

    op.drop_table('job_runs')
    # ### end Alembic commands ###
